config/routes.rb
Pinterest::Application.routes.draw do
  devise_for :users
  resources :pins

  resources :firsts

  get "welcome/index"

  root 'welcome#index'

  

end

app/models/first.rb
class First < ActiveRecord::Base
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	validates :photo, presence:true
	validates :description, presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
 
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :phone) }
  end
end

app/controllers/firsts_controller.rb
class FirstsController < ApplicationController
  before_action :set_first, only: [:show, :edit, :update, :destroy]

  # GET /firsts
  # GET /firsts.json
  def index
    @firsts = First.all
  end

  # GET /firsts/1
  # GET /firsts/1.json
  def show
  end

  # GET /firsts/new
  def new
    @first = First.new
  end

  # GET /firsts/1/edit
  def edit
  end

  # POST /firsts
  # POST /firsts.json
  def create
    @first = First.new(first_params)

    respond_to do |format|
      if @first.save
        format.html { redirect_to @first, notice: 'First was successfully created.' }
        format.json { render action: 'show', status: :created, location: @first }
      else
        format.html { render action: 'new' }
        format.json { render json: @first.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /firsts/1
  # PATCH/PUT /firsts/1.json
  def update
    respond_to do |format|
      if @first.update(first_params)
        format.html { redirect_to @first, notice: 'First was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @first.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firsts/1
  # DELETE /firsts/1.json
  def destroy
    @first.destroy
    respond_to do |format|
      format.html { redirect_to firsts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_first
      @first = First.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def first_params
      params.require(:first).permit(:pins)
    end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except:[ :index, :show]
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)
    @pin.user_id = current_user.id
    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:photo, :description, :name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/firsts_helper.rb
module FirstsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/firsts/_form.html.erb
<%= form_for(@first) do |f| %>
  <% if @first.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@first.errors.count, "error") %> prohibited this first from being saved:</h2>

      <ul>
      <% @first.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pins %><br>
    <%= f.text_field :pins %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/firsts/edit.html.erb
<h1>Editing first</h1>

<%= render 'form' %>

<%= link_to 'Show', @first %> |
<%= link_to 'Back', firsts_path %>

app/views/firsts/index.html.erb
<h1>Listing firsts</h1>

<table>
  <thead>
    <tr>
      <th>Pins</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @firsts.each do |first| %>
      <tr>
        <td><%= first.pins %></td>
        <td><%= link_to 'Show', first %></td>
        <td><%= link_to 'Edit', edit_first_path(first) %></td>
        <td><%= link_to 'Destroy', first, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New First', new_first_path %>

app/views/firsts/new.html.erb
<h1>New first</h1>

<%= render 'form' %>

<%= link_to 'Back', firsts_path %>

app/views/firsts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pins:</strong>
  <%= @first.pins %>
</p>

<%= link_to 'Edit', edit_first_path(@first) %> |
<%= link_to 'Back', firsts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Mi Pinterest</title>

  <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>


	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>

<body>
	<%= render 'shared/navbar'%>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<%= yield %>

</body>
</html>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="form-group">
  <div class="field">
    <%= f.label :name, "Nombre" %><br>
    <%= f.text_field :name, :class => 'form-control', :placeholder => "Nombre del Pin" %>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <%= f.label :photo, "Foto" %><br>
    <%= f.text_field :photo, :class => 'form-control', :placeholder => "Url de la foto" %>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <%= f.label :description, "Descripción" %><br>
    <%= f.text_area :description, :class => 'form-control', :rows => "5", :cols => "30" %>
  </div>
</div>

  <div class="actions">
    <%= f.submit "Crear", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="container">
	<h1>Editing pin</h1>
	<div class="row">
		<div class="col-md-6">
			<%= render 'form' %>
		</div>
	</div>
		<p><%= link_to 'Show', @pin %> |
		<%= link_to 'Back', pins_path %></p>
</div>

app/views/pins/index.html.erb
<div class="container">
  <h1>Listing Pins</h1>
  <% @pins.each do |pin| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= pin.name %>
        <%= image_tag (pin.photo), :class => 'img-responsive' %>
        <%= pin.description %>
        <div class="buttons" style="margin-top:10px; margin-bottom:10px">
          <%= link_to 'Show', pin, :class => 'btn' %>
          <%= link_to 'Edit', edit_pin_path(pin), :class => 'btn' %>
          <% if user_signed_in?%>
            <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <br>
  <% if user_signed_in? %>
    <%= link_to 'New Pin', new_pin_path %>
  <% end %>
</div>

app/views/pins/new.html.erb
<div class="container">
	<h1>Crea un nuevo Pin</h1>
	<div class="row">
		<div class="col-md-6">
			<%= render 'form' %>
		</div>
	</div>
	<p><%= link_to 'Back', pins_path %></p>
</div>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pin.name %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag(@pin.photo, :style=>"width:500px") %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation" style=" margin-bottom: 0px;">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= root_path %>">Mi pinterest</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><a href="#">Nosotros</a></li>
      <li><a href="<%= pins_path%>">Pins</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
          <li class="divider"></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <% if current_user.nil? %> 
          <li><a href="<%= new_user_session_path %>"> Ingreso </a></li>
          <li><a href="<%= new_user_registration_path %>"> Registro </a></li>
        <% else %>
          <li><a href="<%= destroy_user_session_path %>" data-method="delete"> Salir </a></li>
        <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/welcome/index.html.erb
<div class="jumbotron">
	<div class="container">
		<h1 class="titulos"> Mi</h1>
		<h1 class="titulos"> Pinterest</h1>
		<a href="https://www.en1mes.com" class="btn btn-default"> 
		<span class="glyphicon glyphicon-play-circle" style="color:orange"></span>
		Musica 

		</a>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-4">
			<div class="page-header">
 				 <h2 style="display: inline">Inicio</h2>
 				 <span class="label label-default">New</span>
			</div>
			<p class="titulos"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		</div>

		<div class="col-md-4">
			<div class="page-header">
 				 <h2 style="display: inline">Quienes Somos?</h2>
 				 <span class="label label-default">New</span>
			</div>
			<p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

			<img src="http://cdn.wall88.com/51a2ff1e6260752728.jpg" class="img-responsive" >
		</div>

		<div class="col-md-4">
			<div class="page-header">
 				 <h2 style="display: inline">Contacto</h2>
 				 <span class="label label-default">New</span>
			</div>
			<p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

			<a href="https://www.en1mes.com" target="_blank">
				<img src="https://www.en1mes.com/assets/logo-79cc18afeb892865eb97c6b6641f7dc5.png" alt="logo de en 1 mes" class="img-responsive">
			</a>

			<hr>
			<br>

			

			<ol>
				<li> Item 1</li>
				<li> Item 2</li>
				<li> Item 3</li>
			</ol>
		</div>
	</div>
</div>